### ISSUE TITLE
gitignore .DS_Store

### ISSUE THREAD

**Issue by soumyaray** [BlueStarAshes/Share_learning#9]
Put `.DS_Store` in your `. gitignore` -- the file is created on Macs by the OS and should not be in your repo.

**Comment by blureze** [comment]
Thanks for the comment. I've add .DS_Store in .gitignore on the branch "first_refactoring". We'll merge the branch to master after finishing refactoring.

**Comment by soumyaray** [comment]
cool.  thanks! 👍
